/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class matrix_Matrix */

#ifndef _Included_matrix_Matrix
#define _Included_matrix_Matrix
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     matrix_Matrix
 * Method:    transpose
 * Signature: (Ljava/nio/DoubleBuffer;Ljava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_matrix_Matrix_transpose
        (JNIEnv *, jclass, jobject, jobject, jint, jint);

/*
 * Class:     matrix_Matrix
 * Method:    multiply
 * Signature: (Ljava/nio/DoubleBuffer;Ljava/nio/DoubleBuffer;Ljava/nio/DoubleBuffer;III)V
 */
JNIEXPORT void JNICALL Java_matrix_Matrix_multiply__Ljava_nio_DoubleBuffer_2Ljava_nio_DoubleBuffer_2Ljava_nio_DoubleBuffer_2III
        (JNIEnv *, jclass, jobject, jobject, jobject, jint, jint, jint);

/*
 * Class:     matrix_Matrix
 * Method:    multiply
 * Signature: (Ljava/nio/DoubleBuffer;Ljava/nio/DoubleBuffer;Ljava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_matrix_Matrix_multiply__Ljava_nio_DoubleBuffer_2Ljava_nio_DoubleBuffer_2Ljava_nio_DoubleBuffer_2II
        (JNIEnv *, jclass, jobject, jobject, jobject, jint, jint);

/*
 * Class:     matrix_Matrix
 * Method:    multiply
 * Signature: (Ljava/nio/DoubleBuffer;Ljava/nio/DoubleBuffer;DDD)V
 */
JNIEXPORT void JNICALL Java_matrix_Matrix_multiply__Ljava_nio_DoubleBuffer_2Ljava_nio_DoubleBuffer_2DDD
        (JNIEnv *, jclass, jobject, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     matrix_Matrix
 * Method:    add
 * Signature: (Ljava/nio/DoubleBuffer;Ljava/nio/DoubleBuffer;Ljava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_matrix_Matrix_add__Ljava_nio_DoubleBuffer_2Ljava_nio_DoubleBuffer_2Ljava_nio_DoubleBuffer_2II
        (JNIEnv *, jclass, jobject, jobject, jobject, jint, jint);

/*
 * Class:     matrix_Matrix
 * Method:    add
 * Signature: (Ljava/nio/DoubleBuffer;Ljava/nio/DoubleBuffer;DII)V
 */
JNIEXPORT void JNICALL Java_matrix_Matrix_add__Ljava_nio_DoubleBuffer_2Ljava_nio_DoubleBuffer_2DII
        (JNIEnv *, jclass, jobject, jobject, jdouble, jint, jint);

/*
 * Class:     matrix_Matrix
 * Method:    subtract
 * Signature: (Ljava/nio/DoubleBuffer;Ljava/nio/DoubleBuffer;Ljava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_matrix_Matrix_subtract
        (JNIEnv *, jclass, jobject, jobject, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
