/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class matrix_MatrixOperations */

#ifndef _Included_matrix_MatrixOperations
#define _Included_matrix_MatrixOperations
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     matrix_MatrixOperations
 * Method:    transpose
 * Signature: (Ljava/nio/DoubleBuffer;Ljava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_matrix_MatrixOperations_transpose
  (JNIEnv *, jclass, jobject, jobject, jint, jint);

/*
 * Class:     matrix_MatrixOperations
 * Method:    multiply
 * Signature: (Ljava/nio/DoubleBuffer;Ljava/nio/DoubleBuffer;Ljava/nio/DoubleBuffer;III)V
 */
JNIEXPORT void JNICALL Java_matrix_MatrixOperations_multiply__Ljava_nio_DoubleBuffer_2Ljava_nio_DoubleBuffer_2Ljava_nio_DoubleBuffer_2III
  (JNIEnv *, jclass, jobject, jobject, jobject, jint, jint, jint);

/*
 * Class:     matrix_MatrixOperations
 * Method:    multiplyAndAdd
 * Signature: (Ljava/nio/DoubleBuffer;Ljava/nio/DoubleBuffer;Ljava/nio/DoubleBuffer;III)V
 */
JNIEXPORT void JNICALL Java_matrix_MatrixOperations_multiplyAndAdd
  (JNIEnv *, jclass, jobject, jobject, jobject, jint, jint, jint);

/*
 * Class:     matrix_MatrixOperations
 * Method:    multiply
 * Signature: (Ljava/nio/DoubleBuffer;Ljava/nio/DoubleBuffer;Ljava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_matrix_MatrixOperations_multiply__Ljava_nio_DoubleBuffer_2Ljava_nio_DoubleBuffer_2Ljava_nio_DoubleBuffer_2II
  (JNIEnv *, jclass, jobject, jobject, jobject, jint, jint);

/*
 * Class:     matrix_MatrixOperations
 * Method:    multiply
 * Signature: (Ljava/nio/DoubleBuffer;Ljava/nio/DoubleBuffer;DDD)V
 */
JNIEXPORT void JNICALL Java_matrix_MatrixOperations_multiply__Ljava_nio_DoubleBuffer_2Ljava_nio_DoubleBuffer_2DDD
  (JNIEnv *, jclass, jobject, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     matrix_MatrixOperations
 * Method:    add
 * Signature: (Ljava/nio/DoubleBuffer;Ljava/nio/DoubleBuffer;Ljava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_matrix_MatrixOperations_add__Ljava_nio_DoubleBuffer_2Ljava_nio_DoubleBuffer_2Ljava_nio_DoubleBuffer_2II
  (JNIEnv *, jclass, jobject, jobject, jobject, jint, jint);

/*
 * Class:     matrix_MatrixOperations
 * Method:    add
 * Signature: (Ljava/nio/DoubleBuffer;Ljava/nio/DoubleBuffer;DII)V
 */
JNIEXPORT void JNICALL Java_matrix_MatrixOperations_add__Ljava_nio_DoubleBuffer_2Ljava_nio_DoubleBuffer_2DII
  (JNIEnv *, jclass, jobject, jobject, jdouble, jint, jint);

/*
 * Class:     matrix_MatrixOperations
 * Method:    subtract
 * Signature: (Ljava/nio/DoubleBuffer;Ljava/nio/DoubleBuffer;Ljava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_matrix_MatrixOperations_subtract
  (JNIEnv *, jclass, jobject, jobject, jobject, jint, jint);

/*
 * Class:     matrix_MatrixOperations
 * Method:    dot
 * Signature: (Ljava/nio/DoubleBuffer;Ljava/nio/DoubleBuffer;I)D
 */
JNIEXPORT jdouble JNICALL Java_matrix_MatrixOperations_dot
  (JNIEnv *, jclass, jobject, jobject, jint);

/*
 * Class:     matrix_MatrixOperations
 * Method:    outer
 * Signature: (Ljava/nio/DoubleBuffer;Ljava/nio/DoubleBuffer;Ljava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_matrix_MatrixOperations_outer
  (JNIEnv *, jclass, jobject, jobject, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
